 # A sample Gemfile
 source "http://rubygems.org"
 
 gem 'sinatra'
 gem 'sinatra-contrib'
 gem 'json'
 gem 'resque'
 gem 'thin'
 gem 'unicorn'
 gem 'net-sftp'
 gem "backports", "~> 2.3.0"
 gem 'rake'
